CREATE TABLE CLIENTE (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100),
    img_src VARCHAR(200),
    badges VARCHAR(200),
    ingredients VARCHAR(200),
    tab_prepare VARCHAR(200),
    tab_comments VARCHAR(200),
    tab_others VARCHAR(200)
);

-- CREATE TABLE PRODUTO (
--     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
--     DESCRICAO VARCHAR(100),
--     PRECO_UNITARIO NUMERIC(20,2)
-- );

-- CREATE TABLE PEDIDO (
--     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
--     CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
--     DATA_PEDIDO TIMESTAMP,
--     STATUS VARCHAR(20)
--     TOTAL NUMERIC(20,2)
-- );

-- CREATE TABLE ITEM_PEDIDO (
--     ID INTEGER PRIMARY KEY AUTO_INCREMENT,
--     PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
--     PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
--     QUANTIDADE INTEGER
-- );
